name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Initialize Firebase (if needed)
        run: |
          # Only run this if you don't have firebase.json in your repo
          # firebase init hosting

      - name: Authenticate with Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json

      - name: Deploy to Firebase
        run: firebase deploy --project abc-club-204c1 --only hosting
